image: ubuntu:18.04

stages:
  - build
#  - test
#  - package

build:
  stage: build
  before_script:
    - apt-get update && apt-get -y install git build-essential cmake libboost-all-dev libssl-dev zlib1g-dev
    - git submodule sync --recursive
    - git submodule update --init --recursive
  artifacts:
    untracked: true
  script:
    - cd Source && mkdir build && cd build && cmake .. && make
