image: ubuntu:18.04

stages:
  - build_coverage
  - test
#  - package

build_coverage:
  stage: build_coverage
  before_script:
    - apt-get update && apt-get -y install git build-essential cmake libboost-all-dev libssl-dev zlib1g-dev
    - git submodule sync --recursive
    - git submodule update --init --recursive
  artifacts:
    untracked: true
  script:
    - cd Source && mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS='-O0 -g -pg -fprofile-arcs -ftest-coverage' -DCMAKE_EXE_LINKER_FLAGS=-pg -DCMAKE_SHARED_LINKER_FLAGS=-pg .. && make

test:
  stage: test
  before_script:
    - apt-get update && apt-get -y install lcov curl libboost-all-dev libssl-dev zlib1g-dev
  dependencies:
    - build_coverage
  artifacts:
    untracked: true
  script:
    - cd Source/build
    - sh -c './test_Coverage'
    - lcov -d . -c --output-file app.info
    - lcov -l app.info
